Contribution for Issue #127
palewire/moneyinpolitics.wtf pull request #200
Opened 2024-11-30 22:45 UTC by Lorxus

Adding an example of "(campaign) contribution" in use in the wild. Issue #127

2024-12-01 11:22 UTC, palewire commented
Thank you for this, though the example includes the plural form of the word, contributions. We try to only use the precise word in our examples, in this case that would be contribution.

2024-12-01 11:28 UTC, palewire requested changes
We need a singular use of "contribution" rather than the plural use of "contributions."

2025-03-01 09:19 UTC, palewire commented
Thank you for this "contribution!"

2025-03-01 09:19 UTC, merged

2025-03-01 12:44 UTC, Lorxus commented
> Thank you for this "contribution!"

A pleasure - thanks for providing this as a way to cut your teeth on the basics of git!